### ISSUE TITLE
Script errors

### ISSUE THREAD

**Issue by dankerpepers** [LittleBigBug/Flat-Custom-UI-Pack#1]
When you come close enough to a bot to see the hud over their head you get this error:

[ERROR] addons/flat-customui/lua/ui/cl_headinfo.lua:35: attempt to concatenate a nil value
1. fn - addons/flat-customui/lua/ui/cl_headinfo.lua:35
   1. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

**Comment by dankerpepers** [comment]
Actually its not only bots

**Comment by LittleBigBug** [comment]
Fixed
https://github.com/LittleBigBug/Flat-Custom-UI-Pack/commit/f3946a19a490c115c5f501be018cfd64905503b7
